### PR TITLE
Create main.yml

### PR DESCRIPTION
**Pull request by qz267**
Init main.yml and added virtualenv build for the crawler.

### CODE REVIEW

**Comment by qz267** [comment]
[Setup scrapyd to enable execute crawler as a service](https://trello.com/c/VojduiCq/14-setup-scrapyd-to-enable-execute-crawler-as-a-service)

**Comment by qz267** [comment]
@Edward-MC ping

**Comment by qz267** [comment]
[Setup crawler github action to build the virtualenv](https://trello.com/c/t6f4myrg/26-setup-crawler-github-action-to-build-the-virtualenv)

**Review by Edward-MC — COMMENTED** [review]
Approve

**Pull request merged**
